chore: upgrade to Tractus-X EDC 0.12.0 (#370)
* chore: Upgrade to Tractus-X EDC 0.11.0 to 0.12.0

* chore: Harmonize versions and build config with tractusx-edc

* chore: Fixes dependency issues after shadowJar upgrade

* chore: Fix NoClassDefFoundError by excluding lib

* chore: Switch to json-ld-core and remove duplicate classes

* chore: Use latest TX EDC rc4 and use TX dataplane-util

* chore: Switch to Wiremock like midstream

* chore: Rename FX DSP to fx-legacy-dataspace-protocol

* chore: Bump to latest RC5 and remove dependencies

* Remove TX dataspace-protocol-core until
  eclipse-tractusx/tractusx-edc#2597 is solved.
* Remove samples:multi-tenancy

* chore: re-add registration of dsp-spi-v2025

* chore: exclude org.eclipse.edc:data-plane-util

* chore: Bump to TX EDC 0.12.0

* chore: Fix E2E test CatalogTest

* chore: fix property name after TX EDC migration

* chore: Temporarily disable CatalogTest